- alias: Update Tesla location as MQTT location updates
  initial_state: true
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/latitude
  - platform: mqtt
    topic: teslamate/cars/1/longitude
  action:
  - service: device_tracker.see
    data_template:
      dev_id: tesla_location
      gps:
      - '{{ states.sensor.tesla_latitude.state }}'
      - '{{ states.sensor.tesla_longitude.state }}'
  id: 60bbbc7b8b5d4b4fb6e0bf039768570a
- id: 30c266f9-b727-4cef-9597-07300fe2da0b
  alias: CAC Reminder Garage Door
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.mudroom_door
    from: 'off'
    to: 'on'
  condition:
  - alias: Workday
    condition: time
    before: 08:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 00:00:00
  - alias: Tesla Home
    condition: state
    entity_id: device_tracker.tesla_location
    state: home
  - condition: state
    entity_id: input_boolean.on_leave_or_teleworking
    state: 'off'
  action:
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.garage
      volume: 0.7
      message: Good morning, Geoffrey. It looks like you are headed to work. Please
        make sure you did not forget your cack!
- id: 0088bf22-23a8-4154-8fec-9cc0f4e21571
  alias: Announce Car Unplugged
  trigger:
  - platform: time
    at: input_datetime.tesla_charging_check
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.tesla_location
      state: home
    - condition: state
      state: 'off'
      entity_id: binary_sensor.tesla_plugged_in
    - condition: time
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      before: 00:00:00
      after: 00:00:00
    - condition: numeric_state
      entity_id: sensor.tesla_est_battery_range_mi
      below: 198.6
  action:
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.kitchen
      volume: 0.6
      message: "{{ [\n  'Pardon me, ',\n  'Excuse me, ',\n  'I do not mean to interrupt,
        but,',\n  'I hate to interrupt, but,',\n  'I beg your pardon, ',\n  'I do
        not mean to intrude, but, ',\n  'I am sorry to interrupt, but. ',\n  'Just
        a quick heads up, '\n  ] | random }}\n{{ [\n  'the Tesla is not plugged in.',\n
        \ 'your car needs to be plugged in for you to make it to work tomorrow.',\n
        \ 'plugging in your car tonight will save you on supercharging.',\n  'the
        Tesla is unplugged. I would plug it in for you. But I lack legs. And Arms.'\n
        \   ] | random }}"
  initial_state: true
- id: '1670369323535'
  alias: Buffet Christmas lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
    id: Sunset
  - platform: time
    at: '23:00:00'
    id: Midnight
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Sunset
      sequence:
      - type: turn_on
        device_id: 3fbd83da1a9d47c93117aaf4f18770bf
        entity_id: switch.lumi_lumi_plug_maus01_switch_2
        domain: switch
    - conditions:
      - condition: trigger
        id: Midnight
      sequence:
      - type: turn_off
        device_id: 3fbd83da1a9d47c93117aaf4f18770bf
        entity_id: switch.lumi_lumi_plug_maus01_switch_2
        domain: switch
  mode: single
- id: '1680543685838'
  alias: Leave/Telework Switch On
  description: This automation triggers if Geoff is on leave or teleworking to alter
    other automations.
  trigger:
  - platform: time
    at: 03:00:00
  condition:
  - condition: state
    entity_id: calendar.geoff_leave_and_telework
    state: 'on'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.on_leave_or_teleworking
  mode: single
- id: '1681312852471'
  alias: Sleep Type Selector
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
    variables:
      tariff: nap
  - platform: time
    at: '17:00:00'
    variables:
      tariff: bed
  condition: []
  action:
  - service: select.select_option
    data:
      option: '{{ tariff }}'
    target:
      entity_id: select.avery_daily_sleep
  - service: select.select_option
    data:
      option: '{{ tariff }}'
    target:
      entity_id: select.benjamin_daily_sleep
  mode: single
- id: '1681324323411'
  alias: Leave/Teleworking Reset
  description: ''
  trigger:
  - platform: time
    at: '23:30:00'
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.on_leave_or_teleworking
  mode: single
- id: '1681501102093'
  alias: New Automation
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.kitchen_2
    data:
      media_content_id: media-source://media_source/local/09 - Against The Wind.mp3
      media_content_type: audio/mpeg
    metadata:
      title: 09 - Against The Wind.mp3
      thumbnail:
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://media_source
  - service: media_player.repeat_set
    data:
      repeat: one
    target:
      entity_id: media_player.kitchen_2
  mode: single
