- alias: Update Tesla location as MQTT location updates
  initial_state: true
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/latitude
  - platform: mqtt
    topic: teslamate/cars/1/longitude
  action:
  - service: device_tracker.see
    data_template:
      dev_id: tesla_location
      gps:
      - '{{ states.sensor.tesla_latitude.state }}'
      - '{{ states.sensor.tesla_longitude.state }}'
  id: 60bbbc7b8b5d4b4fb6e0bf039768570a
- id: 30c266f9-b727-4cef-9597-07300fe2da0b
  alias: CAC Reminder Garage Door
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.mudroom_door
    from: 'off'
    to: 'on'
  condition:
  - alias: Workday
    condition: time
    before: 08:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 00:00:00
  - alias: Tesla Home
    condition: state
    entity_id: device_tracker.tesla_location
    state: home
  action:
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.garage
      volume: 0.7
      message: Good morning, Geoffrey. It looks like you are headed to work. Please
        make sure you did not forget your cack!
- id: 0088bf22-23a8-4154-8fec-9cc0f4e21571
  alias: Announce Car Unplugged
  trigger:
  - platform: time
    at: input_datetime.tesla_charging_check
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.tesla_location
      state: home
    - condition: state
      state: 'off'
      entity_id: binary_sensor.tesla_plugged_in
    - condition: time
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      before: 00:00:00
      after: 00:00:00
    - condition: numeric_state
      entity_id: sensor.tesla_est_battery_range_mi
      below: 198.6
  action:
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.kitchen
      volume: 0.6
      message: "{{ [\n  'Pardon me, ',\n  'Excuse me, ',\n  'I do not mean to interrupt,
        but,',\n  'I hate to interrupt, but,',\n  'I beg your pardon, ',\n  'I do
        not mean to intrude, but, ',\n  'I am sorry to interrupt, but. ',\n  'Just
        a quick heads up, '\n  ] | random }}\n{{ [\n  'the Tesla is not plugged in.',\n
        \ 'your car needs to be plugged in for you to make it to work tomorrow.',\n
        \ 'plugging in your car tonight will save you on supercharging.',\n  'the
        Tesla is unplugged. I would plug it in for you. But I lack legs. And Arms.'\n
        \   ] | random }}"
  initial_state: true
