# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  db_url: !secret mariadb_url

  # Text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_key
    aws_secret_access_key: !secret aws_secret
    region_name: "us-east-1"
    text_type: ssml
    voice: Matthew
    cache: True
    engine: neural

proximity:
  home_tesla:
    zone: home
    devices:
      - device_tracker.tesla_location
    tolerance: 15
    unit_of_measurement: mi

mqtt:
  sensor: !include mqtt_sensor.yaml
  binary_sensor: !include mqtt_binary_sensor.yaml

utility_meter:
  avery_daily_nap:
    source: sensor.avery_nap
    name: Avery Daily Nap
    cycle: daily
    offset:
      hours: 9
  benjamin_daily_nap:
    source: sensor.benjamin_nap
    name: Benjamin Daily Nap
    cycle: daily
    offset:
      hours: 9

template:
  - sensor:
      - name: trash_days
        unique_id: c16bb989-0f74-4fb0-b105-fe039b7fbfc3
        state: >-
          {{ min(((state_attr('calendar.garbage','start_time') | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int, 2) }}
        attributes:
          days: >-
            {{ ((state_attr('calendar.garbage','start_time') | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int }}

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_datetime: !include input_datetime.yaml
frontend:
  themes: !include_dir_merge_named themes
